"""estrutura inicial

Revision ID: b1b6bcf683f3
Revises: 
Create Date: 2026-08-26 16:34:23.809286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b6bcf683f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linha', sa.String(length=255), nullable=False),
    sa.Column('formato', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('imagem_url', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('perfil', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_nome', sa.String(length=255), nullable=False),
    sa.Column('cliente_contato', sa.String(length=255), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('criado', 'aprovado', 'em_producao', 'em_logistica', 'entregue', 'finalizado', 'cancelado'), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('altura_cm', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('largura_cm', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('cor', sa.String(length=100), nullable=True),
    sa.Column('led_direto', sa.Boolean(), nullable=True),
    sa.Column('led_indireto', sa.Boolean(), nullable=True),
    sa.Column('moldura', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('preco_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('variante', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variante_sku'), ['sku'], unique=True)

    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('minimo', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variante_id'], ['variante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variante_id')
    )
    op.create_table('item_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['variante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimento_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estoque_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estoque_id'], ['estoque.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimento_estoque')
    op.drop_table('item_pedido')
    op.drop_table('estoque')
    with op.batch_alter_table('variante', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variante_sku'))

    op.drop_table('variante')
    op.drop_table('pedido')
    op.drop_table('usuario')
    op.drop_table('produto')
    # ### end Alembic commands ###
